"""Схема заявок на расходы

Revision ID: 0001
Revises: 
Create Date: 2026-09-07 13:45:12.093910
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Счётчик номеров заявок: не откатывается, поэтому номер
    # удалённого черновика не достанется другой заявке.
    op.execute(sa.schema.CreateSequence(sa.Sequence("request_number_seq", start=1)))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity', 'entity_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('EMPLOYEE', 'MANAGER', 'FINANCE', 'ADMIN', name='employee_role', native_enum=False, length=16), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monthly_limit IS NULL OR monthly_limit >= 0', name='ck_employees_limit_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('monthly_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_budget_amount_non_negative'),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='ck_budget_month_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_budget_year_month')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('expense_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'PAID', 'REJECTED', name='request_status', native_enum=False, length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_requests_amount_non_negative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_requests_employee_created', 'expense_requests', ['employee_id', 'created_at'], unique=False)
    op.create_index('ix_requests_status_created', 'expense_requests', ['status', 'created_at'], unique=False)
    op.create_table('expense_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_lines_price_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_lines_quantity_positive'),
    sa.CheckConstraint('total >= 0', name='ck_lines_total_non_negative'),
    sa.ForeignKeyConstraint(['request_id'], ['expense_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lines_request', 'expense_lines', ['request_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('CARD', 'CASH', name='payment_method', native_enum=False, length=8), nullable=False),
    sa.Column('document', sa.String(length=64), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_payments_amount_non_negative'),
    sa.ForeignKeyConstraint(['request_id'], ['expense_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', name='uq_payments_request')
    )
    op.create_table('request_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('CREATED', 'SUBMITTED', 'COMMENTED', 'VIEWED', 'APPROVED', 'AUTO_APPROVED', 'REJECTED', 'PAID', name='event_kind', native_enum=False, length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['expense_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_request_created', 'request_events', ['request_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_request_created', table_name='request_events')
    op.drop_table('request_events')
    op.drop_table('payments')
    op.drop_index('ix_lines_request', table_name='expense_lines')
    op.drop_table('expense_lines')
    op.drop_index('ix_requests_status_created', table_name='expense_requests')
    op.drop_index('ix_requests_employee_created', table_name='expense_requests')
    op.drop_table('expense_requests')
    op.drop_table('projects')
    op.drop_table('monthly_budgets')
    op.drop_table('employees')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSequence(sa.Sequence("request_number_seq")))
