"""Двухфакторная аутентификация

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-07 14:47:26.942540
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'code_hash', name='uq_recovery_employee_code')
    )
    op.create_index('ix_recovery_employee', 'recovery_codes', ['employee_id'], unique=False)
    op.add_column('employees', sa.Column('totp_secret', sa.String(length=255), nullable=True))
    # server_default нужен только на время добавления колонки: у уже
    # заведённых сотрудников второго фактора нет.
    op.add_column(
        'employees',
        sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('employees', 'totp_enabled', server_default=None)
    op.add_column('employees', sa.Column('totp_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('employees', sa.Column('totp_last_step', sa.BigInteger(), nullable=True))
    op.add_column(
        'employees',
        sa.Column('failed_logins', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('employees', 'failed_logins', server_default=None)
    op.add_column('employees', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'locked_until')
    op.drop_column('employees', 'failed_logins')
    op.drop_column('employees', 'totp_last_step')
    op.drop_column('employees', 'totp_confirmed_at')
    op.drop_column('employees', 'totp_enabled')
    op.drop_column('employees', 'totp_secret')
    op.drop_index('ix_recovery_employee', table_name='recovery_codes')
    op.drop_table('recovery_codes')
    # ### end Alembic commands ###
