"""Настройки уведомлений

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-07 15:28:12.901257
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'employees',
        sa.Column('notify_new_requests', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('employees', 'notify_new_requests', server_default=None)
    op.add_column(
        'employees',
        sa.Column('notify_stale_requests', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('employees', 'notify_stale_requests', server_default=None)
    op.add_column(
        'employees',
        sa.Column('notify_weekly_budget', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('employees', 'notify_weekly_budget', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'notify_weekly_budget')
    op.drop_column('employees', 'notify_stale_requests')
    op.drop_column('employees', 'notify_new_requests')
    # ### end Alembic commands ###
