"""Расход на AI: снимок стоимости и кто ответил

Стоимость записывается в момент обращения и больше не меняется: цены
Anthropic меняются, а расход за прошлый месяц не должен пересчитываться
новым прайсом.

Старым записям стоимость задним числом НЕ проставляется. Цена, по которой
за них платили, нам неизвестна, а подставить сегодняшнюю значит выдать
догадку за снимок. Раздел «Расход AI» считает такие записи по нынешней
таблице цен и помечает это как оценку — но в базе догадки не остаётся.

`resolved_by` у старых записей выводится один раз и только там, где вывод
однозначен: заполненная модель означает, что отвечала именно она. Всё
остальное остаётся NULL — «неизвестно», а не выдуманное значение.

Revision ID: 0018
Revises: 0017
Create Date: 2026-09-10
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0018'
down_revision: str | None = '0017'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column('ai_interactions', sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True))
    op.add_column('ai_interactions', sa.Column('resolved_by', sa.Enum('MODEL', 'ALIAS', 'CACHE', name='ai_resolved_by', native_enum=False, length=16), nullable=True))
    op.create_index('ix_ai_model_created', 'ai_interactions', ['model', 'created_at'], unique=False)

    op.execute(
        """
        UPDATE ai_interactions
           SET resolved_by = 'MODEL'
         WHERE model IS NOT NULL
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_model_created', table_name='ai_interactions')
    op.drop_column('ai_interactions', 'resolved_by')
    op.drop_column('ai_interactions', 'cost_usd')
    # ### end Alembic commands ###
